### ISSUE TITLE
 HLS.parse is not a function

### ISSUE THREAD

**Issue by wimil** [jasonbyrne/parse-hls#2]

**Comment by vladshcherbin** [comment]
@jasonbyrne currently it's impossible to use this library with this error

**Comment by jasonbyrne** [comment]
It works. You just need to import HLS, which is exported by this library.

**Comment by vladshcherbin** [comment]
@jasonbyrne no, it does not:

```js
import HLS from 'parse-hls'

console.log(HLS.parse('master'))

```

result:

![error](https://user-images.githubusercontent.com/6711845/120905935-31395b00-c65e-11eb-97d3-00b22634a2c2.png)


node 16.0.0
parse-hls 1.0.7
esm modules

**Comment by jasonbyrne** [comment]
I just did a test, pulling it down from npm into a fresh project

```
import * as fs from "fs";
import HLS from "parse-hls";

const manifest = HLS.parse(fs.readFileSync("./example.m3u8", "utf8"));
console.log(manifest);
```

This worked just fine. TypeScript recognized the HLS.parse and it ran once transpiled to JS.  I don't know why a version would cause an issue but I have

TypeScript Version 4.2.4
Node v14.17.0
parse-hls 1.0.7

**Comment by tugrul** [comment]
```javascript
const {default: HLS} = require('parse-hls');
```
